#!/usr/bin/env bash

##################################################
# Name: ansible
# Description: Git pre-commit hook for Ansible projects
##################################################

SCRIPT="${BASH_SOURCE[0]}"

#########################
# Variables
#########################

ANSIBLE_DIRECTORY="${ANSIBLE_DIRECTORY:=ansible}"
ANSIBLE_LINT_CONFIG="${ANSIBLE_LINT_CONFIG:=.github/linters/.ansible-lint.yml}"
ANSIBLE_VAULT_SCRIPT="${ANSIBLE_VAULT_SCRIPT:=$(pwd)/scripts/crypt.sh}"
ANSIBLE_LINT_ENABLED="FALSE"

export ANSIBLE_DIRECTORY
export ANSIBLE_LINT_CONFIG
export ANSIBLE_VAULT_SCRIPT
export ANSIBLE_LINT_ENABLED

#########################
# Functions
#########################

#########################
# Main
#########################

msg "STARTED: Running ${SCRIPT} Git hook from $(pwd)"

# Ansible Linting
if ! checkBin ansible-lint;
then

	msg "Error, please install ansible-lint!"
	return 1

elif [[ ! -f "${ANSIBLE_LINT_CONFIG}" ]];
then

	msg "Warning, there is no ${ANSIBLE_LINT_CONFIG} file present in this repository, ansible-lint will be skipped."

elif [[ -f "${ANSIBLE_DIRECTORY}/ansible.cfg" ]];
then

	# Move into Ansible directory
	pushd "${ANSIBLE_DIRECTORY}" > /dev/null
	msg "Pushed into Ansible directory"
	ANSIBLE_LINT_ENABLED=TRUE

elif [[ -f "ansible.cfg" ]];
then

	# Already in Ansible directory
	msg "Found ansible.cfg"
	ANSIBLE_LINT_ENABLED=TRUE

fi

if [[ "${ANSIBLE_LINT_ENABLED:-FALSE}" == "TRUE" ]];
then	
	ansible-lint \
		-f rich \
		-c "${ANSIBLE_LINT_CONFIG}" \
		--progressive \
		--show-relpath \
	|| { 
		msg "ansible-lint failed!"
		return 1
	}

	popd > /dev/null 2>&1

else

	msg "Unable to find ansible directory, ansible-lint skipped..."

fi

if [[ -f "${ANSIBLE_VAULT_SCRIPT}" ]];
then

	"${ANSIBLE_VAULT_SCRIPT}" encrypt || {
		msg "Ansible Vault encryption failed!"
		return 1
	}

else

	msg "WARNING: Ansible Vault script not found, skipping encryption checks..."

fi

return 0
