#!/usr/bin/env bash

##################################################
# Name: ansible
# Description: Git pre-commit hook for Ansible projects
##################################################

SCRIPT="${BASH_SOURCE[0]}"

#########################
# Variables
#########################

ANSIBLE_LINT_CONFIG=".github/linters/.ansible-lint.yml"
ANSIBLE_VAULT_SCRIPT="$(pwd)/scripts/crypt.sh"

export ANSIBLE_LINT_CONFIG
export ANSIBLE_VAULT_SCRIPT

#########################
# Functions
#########################

#########################
# Main
#########################

msg "STARTED: Running ${SCRIPT} Git hook from $(pwd)"

# Ansible Linting
if ! checkBin ansible-lint;
then

	msg "Error, please install ansible-lint!"
	return 1

elif [[ ! -f "${ANSIBLE_LINT_CONFIG}" ]];
then

	msg "Warning, there is no ${ANSIBLE_LINT_CONFIG} file present in this repository, ansible-lint will be skipped."

else

	ansible-lint \
		-f rich \
		-c "${ANSIBLE_LINT_CONFIG}" \
		--progressive \
		--show-relpath \
	|| { 
		msg "ansible-lint failed!"
		return 1
	}

fi

if [[ -f "${ANSIBLE_VAULT_SCRIPT}" ]];
then

	"${ANSIBLE_VAULT_SCRIPT}" --encrypt || {
		msg "Ansible Vault encryption failed!"
		return 1
	}

else

	msg "WARNING: Ansible Vault script not found, skipping encryption checks..."

fi

return 0
