#!/usr/bin/env bash

##################################################
# Name: ansible
# Description: Git pre-commit hook for Ansible projects
##################################################

SCRIPT="${BASH_SOURCE[0]}"

#########################
# Variables
#########################

ANSIBLE_DIRECTORY="${ANSIBLE_DIRECTORY:=ansible}"
ANSIBLE_LINT_CONFIG="${ANSIBLE_LINT_CONFIG:=.github/linters/.ansible-lint.yml}"
ANSIBLE_VAULT_SCRIPT="${ANSIBLE_VAULT_SCRIPT:=scripts/crypt.sh}"
ANSIBLE_LINT_ENABLED="FALSE"

export ANSIBLE_DIRECTORY
export ANSIBLE_INVENTORY
export ANSIBLE_LINT_CONFIG
export ANSIBLE_VAULT_SCRIPT
export ANSIBLE_LINT_ENABLED

#########################
# Functions
#########################

#########################
# Main
#########################

msg "STARTED: Running ${SCRIPT} Git hook from $(pwd)"

# Check Vaults are encrypted
if [[ -f "${ANSIBLE_VAULT_SCRIPT}" ]];
then

	msg "Encrypting Vaults"

	"${ANSIBLE_VAULT_SCRIPT}" encrypt || {
		msg "Ansible Vault encryption exited with non-zero. Verify all vaults encrypted!"
		return 1
	}

else

	msg "WARNING: Ansible Vault script not found, skipping encryption checks..."

fi

# Ansible Linting
if ! type ansible-lint >/dev/null;
then

	msg "Error, please install ansible-lint!"
	return 1

elif [[ ! -f "${ANSIBLE_LINT_CONFIG}" ]];
then

	msg "Warning, there is no ${ANSIBLE_LINT_CONFIG} file present in this repository, ansible-lint will be skipped."

elif [[ -f "${ANSIBLE_DIRECTORY}/ansible.cfg" ]];
then

	ANSIBLE_LINT_ENABLED=TRUE

elif [[ -f "ansible.cfg" ]];
then

	# Already in Ansible directory
	msg "Found ansible.cfg"
	ANSIBLE_LINT_ENABLED=TRUE

fi

if [[ "${ANSIBLE_LINT_ENABLED:-FALSE}" == "TRUE" ]];
then

	msg "Running ansible-lint on ${ANSIBLE_DIRECTORY}"

	pushd "${ANSIBLE_DIRECTORY}" || { echo "Failed to push into ${ANSIBLE_DIRECTORY}" ; exit 1 ; }

	ansible-lint \
		-f rich \
		-c "../${ANSIBLE_LINT_CONFIG}" \
		--show-relpath \
		--exclude roles \
		--exclude collections \
	|| { 
		msg "ansible-lint failed, please review the output."
		popd 2>/dev/null
	}
	popd >/dev/null 2>&1

else

	msg "Unable to find ansible directory, ansible-lint skipped..."

fi

return 0
